name: Build and push Docker image

on:
  workflow_dispatch:
  push:

jobs:
  build-and-push:
    name: Docker build and push
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/modrinth/discord-bot
      - name: Login to GitHub Images
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile
